name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    
    - name: build nexus
      run: docker build . --file Dockerfile
      working-directory: nexus

    - uses: raven-oscar/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com

    - name: build haproxy
      run: docker build . --file Dockerfile
      working-directory: haproxy
